Poc dependencies ck merge
enarx/koine pull request #20
Opened 2021-01-24 12:15 UTC by MikeCamel

Fixes #18

Also moves to upstream ciborium

2021-01-24 13:03 UTC, MikeCamel commented
@mbestavros - this is failing on the ring licence.  I believe that we fixed this elsewhere - please could we apply the same fix here?

2021-01-26 11:30 UTC, haraldh commented
err.. these commits should be squashed and the text should have meaningful commit messages

2021-01-26 11:33 UTC, haraldh requested changes

2021-01-26 11:33 UTC, haraldh commented on Cargo.toml
> +#tokio = { version = "1.0", features = ["macros", "sync"] }
with comment?

2021-01-26 11:33 UTC, haraldh commented on src/attestation/sev.rs
> +//taken wholesale for https://github.com/connorkuehl/koine/commit/8659386bbdce554872231636d00a4b94c69f3aa2
?

2021-01-26 11:33 UTC, haraldh commented on src/lib.rs
> +//use std::net::IpAddr;
?

2021-01-26 11:33 UTC, haraldh commented on src/lib.rs
> +*/
?

2021-01-26 11:33 UTC, haraldh commented on src/lib.rs
> +*/
?

2021-01-26 11:33 UTC, haraldh commented on src/lib.rs
> +*/
?

2021-01-26 11:33 UTC, haraldh commented on src/threading/lists.rs
> +use super::super::*;
?

2021-02-02 10:28 UTC, MikeCamel commented on src/lib.rs
> +*/
fixed

2021-02-02 10:28 UTC, MikeCamel commented on src/lib.rs
> +*/
fixed

2021-02-02 10:28 UTC, MikeCamel commented on src/lib.rs
> +*/
fixed

2021-02-02 10:29 UTC, MikeCamel commented on src/lib.rs
> +//use std::net::IpAddr;
fixed

2021-02-02 10:29 UTC, MikeCamel commented on Cargo.toml
> +#tokio = { version = "1.0", features = ["macros", "sync"] }
fixed

2021-02-02 10:31 UTC, MikeCamel commented on src/threading/lists.rs
> +use super::super::*;
removed this file

2021-09-14 14:31 UTC, closed without merging